'use strict';

const fs = require('node:fs');
const path = require('node:path');

const DEFAULT_ROOT = path.resolve(__dirname, '..');
const NOTICE = '<!-- Generated by npm run build from dev/. Do not edit directly. -->';
const MARKERS = Object.freeze({
  css: ['<!-- file-nally:css:start -->', '<!-- file-nally:css:end -->'],
  js: ['<!-- file-nally:js:start -->', '<!-- file-nally:js:end -->'],
});

const normalizeText = (value) => String(value).replace(/\r\n?/g, '\n').replace(/\n*$/, '') + '\n';
const occurrenceCount = (value, needle) => value.split(needle).length - 1;
const indentBlock = (value, spaces) => {
  const prefix = ' '.repeat(spaces);
  return value.split('\n').map((line) => line ? `${prefix}${line}` : '').join('\n');
};

const replaceMarkedBlock = (template, markers, replacement, label) => {
  const [startMarker, endMarker] = markers;
  if (occurrenceCount(template, startMarker) !== 1 || occurrenceCount(template, endMarker) !== 1) {
    throw new Error(`${label} build markers must each appear exactly once`);
  }
  const start = template.indexOf(startMarker);
  const end = template.indexOf(endMarker);
  if (end <= start) throw new Error(`${label} build markers are out of order`);

  const lineStart = template.lastIndexOf('\n', start) + 1;
  const markerLineEnd = template.indexOf('\n', end + endMarker.length);
  const lineEnd = markerLineEnd === -1 ? template.length : markerLineEnd + 1;
  if (template.slice(lineStart, start).trim() || template.slice(end + endMarker.length, lineEnd).trim()) {
    throw new Error(`${label} build markers must be on their own lines`);
  }
  return template.slice(0, lineStart) + replacement + template.slice(lineEnd);
};

const compose = (templateValue, cssValue, jsValue) => {
  let template = normalizeText(templateValue);
  const css = normalizeText(cssValue).slice(0, -1);
  const js = normalizeText(jsValue).slice(0, -1);
  if (/<\/style/i.test(css)) throw new Error('CSS contains </style and cannot be safely inlined');
  if (/<\/script/i.test(js)) throw new Error('JavaScript contains </script and cannot be safely inlined');
  if (!/^<!DOCTYPE html>\n/i.test(template)) throw new Error('Development HTML must start with <!DOCTYPE html>');

  template = replaceMarkedBlock(template, MARKERS.css, `    <style>\n${indentBlock(css, 8)}\n    </style>\n`, 'CSS');
  template = replaceMarkedBlock(template, MARKERS.js, `<script>\n${js}\n</script>\n`, 'JavaScript');
  template = template.replace(/^<!DOCTYPE html>\n/i, (doctype) => `${doctype}${NOTICE}\n`);
  return normalizeText(template);
};

const build = ({ rootDir = DEFAULT_ROOT, check = false } = {}) => {
  const source = {
    template: path.join(rootDir, 'dev', 'file-nally.html'),
    css: path.join(rootDir, 'dev', 'css', 'file-nally.css'),
    js: path.join(rootDir, 'dev', 'js', 'file-nally.js'),
  };
  const outputPath = path.join(rootDir, 'file-nally.html');
  const generated = compose(
    fs.readFileSync(source.template, 'utf8'),
    fs.readFileSync(source.css, 'utf8'),
    fs.readFileSync(source.js, 'utf8'),
  );
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf8') : null;

  if (check) {
    if (current !== generated) throw new Error('file-nally.html is stale; run npm run build');
    return { changed: false, outputPath };
  }
  if (current === generated) return { changed: false, outputPath };

  const temporaryPath = `${outputPath}.tmp-${process.pid}`;
  try {
    fs.writeFileSync(temporaryPath, generated, 'utf8');
    fs.renameSync(temporaryPath, outputPath);
  } finally {
    fs.rmSync(temporaryPath, { force: true });
  }
  return { changed: true, outputPath };
};

const main = () => {
  const args = process.argv.slice(2);
  if (args.some((arg) => arg !== '--check') || args.filter((arg) => arg === '--check').length > 1) {
    throw new Error('Usage: node scripts/build.cjs [--check]');
  }
  const check = args.includes('--check');
  const result = build({ check });
  process.stdout.write(check ? 'file-nally.html is up to date\n' : result.changed ? 'file-nally.html built\n' : 'file-nally.html already up to date\n');
};

if (require.main === module) {
  try {
    main();
  } catch (error) {
    process.stderr.write(`Build failed: ${error.message}\n`);
    process.exitCode = 1;
  }
}

module.exports = Object.freeze({ build, compose, normalizeText });
